// <auto-generated />
using System;
using LandmarkRemarks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LandmarkRemarks.Migrations
{
    [DbContext(typeof(LandmarkDbContext))]
    [Migration("20190430082026_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("LandmarkRemarks.Models.Remark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Note");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Remarks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16e49139-9a7d-411c-92df-7843ffd462fb"),
                            DateCreated = new DateTime(2019, 4, 30, 18, 20, 25, 942, DateTimeKind.Local).AddTicks(9010),
                            Latitude = 123.456,
                            Longitude = 456.78899999999999,
                            Note = "This is a test note",
                            Username = "test1@example.com"
                        });
                });

            modelBuilder.Entity("LandmarkRemarks.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fcca49d-40e0-447a-8bbf-3393b90c06a5"),
                            Name = "Test User 1",
                            Password = "uCLxzS3PxoW0foPjmAKJ/V2OP/OoLe8k19HWi7Jy6zI=",
                            Username = "test1@example.com"
                        },
                        new
                        {
                            Id = new Guid("6eff546c-8112-4ead-8ce6-e77878ef7062"),
                            Name = "Test User 2",
                            Password = "eScFcq3tutWiEOJiTXbcfLnHn7Lu402/WcaX6VfMJKM=",
                            Username = "test2@example.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
